(function(){
 window.ExportView={mount({main,state,initialWorkId=null}){
  const E=Domain.escape;let prepared=null,objectURL=null,busy=false;const currentWork=initialWorkId?state.works.find(w=>w.id===initialWorkId):null;
  const categories=[...Domain.categories,'Pagamento','Desconto / gasto de pessoa','Compromisso futuro'];
  const labelCategory=c=>c==='Desconto / gasto de pessoa'?'Descontos / gastos':c==='Compromisso futuro'?'Compromissos futuros':c;
  const scopeHTML=initialWorkId?`<input type="hidden" name="export-scope" value="one"><div class="form-summary"><span>Obra selecionada</span><strong>${E(currentWork?.name||'Obra')}</strong><small>${E(currentWork?.client||'')}</small></div><input type="hidden" id="export-work" value="${E(initialWorkId)}">`:`<fieldset class="scope-options"><legend class="sr-only">Abrangência do extrato</legend><label><input type="radio" name="export-scope" value="all" checked><span><strong>Todas as obras</strong><small>Resumo geral e extratos separados no mesmo arquivo.</small></span></label><label><input type="radio" name="export-scope" value="one"><span><strong>Uma obra específica</strong><small>Somente a obra escolhida.</small></span></label></fieldset><label class="field" style="margin-top:20px">Obra<select id="export-work" disabled><option value="">Selecione uma obra</option>${state.works.map(w=>`<option value="${E(w.id)}">${E(w.name)}</option>`).join('')}</select></label>`;
  const filterHTML=`<div class="export-filter-block"><div class="export-filter-title"><strong>Conteúdo do relatório</strong><small>Marque somente o que deseja imprimir/exportar.</small></div><div class="export-filter-grid"><label class="export-filter-all"><input type="checkbox" id="filter-all" checked><span>Todos</span></label>${categories.map(c=>`<label><input type="checkbox" name="export-category" value="${E(c)}" checked><span>${E(labelCategory(c))}</span></label>`).join('')}</div></div>`;
  const today=Domain.today(),currentMonth=today.slice(0,7),currentYear=today.slice(0,4);
  const periodHTML=`<div class="export-filter-block"><div class="export-filter-title"><strong>Período / competência</strong><small>Exporte tudo, apenas um mês ou um ano completo.</small></div><div class="export-period-grid"><label class="field">Período<select id="export-period-mode"><option value="all">Todas as competências</option><option value="month">Uma competência mensal</option><option value="year">Um ano</option></select></label><label class="field" id="export-month-wrap" hidden>Competência<input type="month" id="export-month" value="${currentMonth}"></label><label class="field" id="export-year-wrap" hidden>Ano<input type="number" id="export-year" min="2000" max="2100" value="${currentYear}"></label></div></div>`;
  main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">RELATÓRIO DA OBRA</p><h1>${initialWorkId?'Extrato da obra':'Extrato geral de obras'}</h1><p class="subtitle">${initialWorkId?'Escolha o conteúdo e gere o extrato da obra selecionada.':'Exporte todas as obras juntas ou escolha uma obra específica.'}</p></div><span class="demo-badge">FINANCEIRO ÍNTEGRA</span></div>
  <div class="export-grid"><section class="card export-config"><div class="card-head"><div><h2>${initialWorkId?'Relatório financeiro':'O que você quer exportar?'}</h2><p>Você controla quais tipos de lançamento entram no relatório.</p></div></div><div class="export-body">${scopeHTML}${periodHTML}${filterHTML}<div id="export-selection" class="export-selection" aria-live="polite"></div><div class="export-buttons"><button class="btn primary" id="download-pdf">↓ Baixar extrato em PDF</button><button class="btn" id="download-xlsx">↓ Baixar planilha Excel (.xlsx)</button></div><p class="mini-note">Os totais selecionados refletem apenas os itens marcados; o saldo atual da obra continua considerando todos os custos registrados.</p><p id="export-status" class="form-error" role="status" aria-live="polite"></p></div></section>
  <section class="card"><div class="card-head"><div><h2>Compartilhar extrato</h2><p>Lançamentos e totais no corpo da mensagem.</p></div></div><div class="export-body"><div class="share-symbol" aria-hidden="true">↗</div><p class="share-description">Prepare o extrato em texto da seleção ao lado. Nenhum PDF precisa ser anexado.</p><button class="btn" id="prepare-share">Preparar texto para envio</button><div id="share-ready" hidden></div><div class="notice" style="margin-top:22px;margin-bottom:0">O envio será confirmado por você no WhatsApp ou no e-mail. Extratos longos são divididos em partes, sem omitir lançamentos.</div></div></section></div>
  <p class="footnote">Os arquivos refletem os dados atuais desta demonstração. Comprovantes originais não são incorporados ao extrato.</p>`;
  const $=s=>main.querySelector(s),$$=s=>[...main.querySelectorAll(s)],status=(s,bad=false)=>{const p=$('#export-status');if(!p)return;p.textContent=s;p.className=bad?'form-error':'mini-note positive';};
  const chosenCategories=()=>{if($('#filter-all')?.checked)return null;const selected=$$('input[name="export-category"]:checked').map(x=>x.value);if(!selected.length)throw Error('Selecione pelo menos um tipo de lançamento.');return selected;};
  const chosenPeriod=()=>{const mode=$('#export-period-mode')?.value||'all';if(mode==='month'){const month=$('#export-month')?.value||'';if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('Escolha uma competência mensal válida.');return {mode,month};}if(mode==='year'){const year=Number($('#export-year')?.value);if(!Number.isInteger(year)||year<2000||year>2100)throw Error('Informe um ano válido.');return {mode,year};}return {mode:'all'};};
  const selected=()=>{const scope=$('[name=export-scope]:checked')||$('[name=export-scope]'),type=scope.value,id=$('#export-work').value;if(type==='one'&&!id)throw Error('Escolha a obra para gerar o extrato.');return Exports.snapshot(state,type==='all'?null:id,chosenCategories(),chosenPeriod());};
  function clearPrepared(){prepared=null;if(objectURL){URL.revokeObjectURL(objectURL);objectURL=null;}$('#share-ready').hidden=true;$('#share-ready').innerHTML='';$('#prepare-share').hidden=false;}
  function changed(){clearPrepared();status('');const scope=$('[name=export-scope]:checked')||$('[name=export-scope]');const all=scope.value==='all';if($('#export-work').tagName==='SELECT')$('#export-work').disabled=all;const mode=$('#export-period-mode')?.value||'all';if($('#export-month-wrap'))$('#export-month-wrap').hidden=mode!=='month';if($('#export-year-wrap'))$('#export-year-wrap').hidden=mode!=='year';let data;try{data=selected();}catch(err){$('#export-selection').innerHTML=`<p>${E(err.message)}</p>`;return;}const filterText=data.filters?.length?data.filters.map(labelCategory).join(', '):'Todos os tipos',periodText=data.period?.mode==='month'?`Competência ${data.period.month}`:data.period?.mode==='year'?`Ano ${data.period.year}`:'Todas as competências';$('#export-selection').innerHTML=`<div><span>Obras</span><strong>${data.works.length}</strong></div><div><span>Lançamentos selecionados</span><strong>${data.expenses.length}</strong></div><div><span>Total selecionado</span><strong>${Domain.money(Domain.total(data.expenses))}</strong></div><div class="export-filter-summary"><span>Filtro</span><strong>${E(filterText)} · ${E(periodText)}</strong></div>`;}
  async function run(operation){if(busy)return;busy=true;const controls=[...main.querySelectorAll('button,input,select')],previous=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);status('Preparando arquivo…');try{await operation();}catch(err){status('Não foi possível gerar o arquivo. '+err.message,true);}finally{controls.forEach((c,i)=>c.disabled=previous[i]);busy=false;}}
  function showReady(data){clearPrepared();const message=Exports.text(data),parts=Exports.splitText(message);prepared={data,message,parts};$('#share-ready').innerHTML=`<div class="ready-note"><strong>Extrato em texto pronto</strong><span>${parts.length===1?'Mensagem única':parts.length+' partes para enviar, com todos os lançamentos'}</span></div><label class="field">Texto completo<textarea id="share-text" readonly rows="8"></textarea></label><div class="share-buttons" style="margin-top:14px"><button class="btn" id="copy-text">Copiar extrato completo</button></div><label class="field" style="margin-top:16px">Parte que será enviada<select id="share-part">${parts.map((_,i)=>'<option value="'+i+'">Parte '+(i+1)+' de '+parts.length+'</option>').join('')}</select></label><div class="share-buttons" style="margin-top:14px"><button class="btn" id="copy-part">Copiar esta parte</button><a class="btn primary" id="whatsapp-link" target="_blank" rel="noopener noreferrer">Enviar texto pelo WhatsApp</a><a class="btn" id="email-link">Enviar texto por e-mail</a></div><p class="mini-note">Para extratos longos, envie cada parte ou copie o texto completo e cole na sua mensagem.</p><p id="share-status" class="mini-note" role="status"></p>`;$('#share-text').value=message;$('#share-ready').hidden=false;$('#prepare-share').hidden=true;
   const partText=()=>parts.length===1?parts[0]:'EXTRATO - Parte '+(Number($('#share-part').value)+1)+' de '+parts.length+'\n'+parts[Number($('#share-part').value)];
   const update=()=>{const links=Exports.shareLinks(data,partText());$('#whatsapp-link').href=links.whatsapp;$('#email-link').href=links.email;};update();$('#share-part').addEventListener('change',update);
   async function copy(value){try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(value);else{const area=document.createElement('textarea');area.value=value;area.style='position:fixed;opacity:0';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw Error('clipboard');}$('#share-status').textContent='Texto copiado. Cole na sua mensagem.';}catch{$('#share-text').focus();$('#share-text').select();$('#share-status').textContent='Selecione e copie o texto no campo acima.';}}
   $('#copy-text').addEventListener('click',()=>copy(message));$('#copy-part').addEventListener('click',()=>copy(partText()));
  }
  $('[name=export-scope][value=all]')?.addEventListener('change',changed);$('[name=export-scope][value=one]')?.addEventListener('change',changed);$('#export-work')?.addEventListener('change',changed);
  $('#export-period-mode')?.addEventListener('change',changed);$('#export-month')?.addEventListener('change',changed);$('#export-year')?.addEventListener('change',changed);
  $('#filter-all')?.addEventListener('change',e=>{$$('input[name="export-category"]').forEach(c=>c.checked=e.target.checked);changed();});
  $$('input[name="export-category"]').forEach(c=>c.addEventListener('change',()=>{const items=$$('input[name="export-category"]'),allChecked=items.every(x=>x.checked);$('#filter-all').checked=allChecked;changed();}));
  $('#download-pdf').addEventListener('click',()=>run(async()=>{const data=selected(),blob=await Exports.pdf(data);Exports.download(blob,Exports.filename(data,'pdf'));status('PDF gerado. O download foi solicitado ao navegador.');}));
  $('#download-xlsx').addEventListener('click',()=>run(async()=>{const data=selected(),blob=await Exports.xlsx(data);Exports.download(blob,Exports.filename(data,'xlsx'));status('Planilha gerada. O download foi solicitado ao navegador.');}));
  $('#prepare-share').addEventListener('click',()=>run(async()=>{const data=selected();showReady(data);status('Texto preparado para compartilhar.');}));
  changed();return ()=>{if(objectURL)URL.revokeObjectURL(objectURL);};
 }};
})();
